### ISSUE TITLE
Run bug application Docker unable to select packages

### ISSUE THREAD

**Issue by tomekkowalczyk** [jorge07/symfony-4-es-cqrs-boilerplate#226] opened 2021-11-24 20:10 UTC
branch symfony-5

![image](https://user-images.githubusercontent.com/39382654/143306736-65279507-5eac-4a82-8de7-1c58aacb6b24.png)

**Comment by jorge07** [comment] 2021-11-25 09:51
https://github.com/jorge07/alpine-php/releases/tag/25-11-2021

Feeling a bit like https://www.youtube.com/watch?v=AbSehcT19u0

**Comment by jorge07** [comment] 2021-11-25 10:15
it should be fixed now.
thanks a lot for report this one. Wasn't a 2 min fix

**Closed as completed** 2021-11-25 10:14 UTC

**Comment by tomekkowalczyk** [comment] 2021-11-29 18:19
@jorge07 how let's launch this application we have port 80 in docker-compose, so we should run through 127.0.0.1? I tried local address too.

**Comment by jorge07** [comment] 2021-11-29 21:32
Can you provide curl output and docker logs?

**Comment by tomekkowalczyk** [comment] 2021-12-01 15:09
Hi @jorge07
thanks for the answer, of course I send in the attachment

![image](https://user-images.githubusercontent.com/39382654/144259424-00641d2e-1378-4357-81b9-c5bc811733d4.png)
![image](https://user-images.githubusercontent.com/39382654/144259334-03195034-eb05-4d6e-b265-c6cdf13333e5.png)
![image](https://user-images.githubusercontent.com/39382654/144259469-2e49b0ba-4b2a-402d-ac1f-ae7290a38044.png)
![image](https://user-images.githubusercontent.com/39382654/144259569-53a91eea-d607-477c-a24d-bcb340019c26.png)
![image](https://user-images.githubusercontent.com/39382654/144259630-2def0f3a-2b9a-46af-8b74-a4400f6afae4.png)
![image](https://user-images.githubusercontent.com/39382654/144259718-0eda1aa3-b447-45fa-b109-d5e0845471c2.png)
![image](https://user-images.githubusercontent.com/39382654/144259764-2085692d-fb7f-4cd1-b19a-5de1baad559e.png)

**Comment by jorge07** [comment] 2021-12-13 11:50
I've tested locally a fresh clone and I can't reproduce the issue.

```
    ~/work/github/jorge07/symfony-5-es-cqrs-boilerplate    symfony-5 !2  docker logs symfony-5-es-cqrs-boilerplate-workers_users-1                                                                                                                                                                                                                                                                                                                                           INT ✘ 

 [OK] Consuming messages from transports "users".                               

 // The worker will automatically exit once it has received a stop signal via   
 // the messenger:stop-workers command.                                         

 // Quit the worker with CONTROL-C.                                             

    ~/work/github/jorge07/symfony-5-es-cqrs-boilerplate    symfony-5 !2  docker ps                                                                                                                                                                                                                                                                                                                                                                                               ✔ 
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED              STATUS              PORTS                                                                                                                                                 NAMES
4aea24775312   nginx:1.17-alpine                                      "nginx -g 'daemon of…"   About a minute ago   Up About a minute   0.0.0.0:80->80/tcp, :::80->80/tcp                                                                                                                     symfony-5-es-cqrs-boilerplate-nginx-1
b8c17ff6cf13   symfony-5-es-cqrs-boilerplate_php                      "/sbin/tini -- super…"   About a minute ago   Up About a minute   9000/tcp, 9003/tcp, 0.0.0.0:2323->22/tcp, :::2323->22/tcp                                                                                             symfony-5-es-cqrs-boilerplate-php-1
5f47746d3fb3   symfony-5-es-cqrs-boilerplate_workers_users            "/sbin/tini -- /app/…"   About a minute ago   Up About a minute   22/tcp, 9000/tcp, 9003/tcp                                                                                                                            symfony-5-es-cqrs-boilerplate-workers_users-1
6bafcc52c5d4   symfony-5-es-cqrs-boilerplate_code                     "/sbin/tini -- super…"   About a minute ago   Up About a minute   22/tcp, 9000/tcp, 9003/tcp                                                                                                                            symfony-5-es-cqrs-boilerplate-code-1
3bb1b1bb3ad2   symfony-5-es-cqrs-boilerplate_workers_events           "/sbin/tini -- /app/…"   About a minute ago   Up About a minute   22/tcp, 9000/tcp, 9003/tcp                                                                                                                            symfony-5-es-cqrs-boilerplate-workers_events-1
81d51086f976   docker.elastic.co/elasticsearch/elasticsearch:7.11.0   "/bin/tini -- /usr/l…"   2 minutes ago        Up 2 minutes        0.0.0.0:9200->9200/tcp, :::9200->9200/tcp, 9300/tcp                                                                                                   symfony-5-es-cqrs-boilerplate-elasticsearch-1
6ef9e74c76cc   rabbitmq:3-management                                  "docker-entrypoint.s…"   2 minutes ago        Up 2 minutes        4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, :::5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp, :::15672->15672/tcp   symfony-5-es-cqrs-boilerplate-rmq-1
886283654b2b   mysql:8.0                                              "docker-entrypoint.s…"   2 minutes ago        Up 2 minutes        0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp                                                                                                  symfony-5-es-cqrs-boilerplate-mysql-1
9cd1b7ece8f2   docker.elastic.co/kibana/kibana:7.11.0                 "/bin/tini -- /usr/l…"   2 days ago           Up About a minute   0.0.0.0:5601->5601/tcp, :::5601->5601/tcp                                                                                                             symfony-5-es-cqrs-boilerplate-kibana-1
```

Can you provide OS and docker version to see if I can emulate? thanks

**Comment by tomekkowalczyk** [comment] 2021-12-13 14:16
@jorge07 
Docker Engine v20.10.8
Windows 10 WSL 2

**Comment by jorge07** [comment] 2021-12-13 23:34
Can you start one of those containers and do an ls in the workdir? Seems volume binding is wrong somehow
